### PR TITLE
This is initial commit of reorganizing project for Maven support. Top…

### PR DESCRIPTION
**Pull request by archenroot**
… project is Maven Aggregator which includes subfolders of Parent template and real modules - only core is really functional.

TODO:
- Configure properly build plugins
- With new version of LWJGL I will generate new lwjgl platform dependencies and load them into my private Nexus repo.
- Documentation plugin will be configured, need to check what to do with current docs folder, if it is more static or dynamic (could be generated from source code)

### CODE REVIEW

**Comment by archenroot** [comment]
I think we should move this temporarily into new branch, I created one "feature/maven" for example, until it is stable

**Comment by archenroot** [comment]
Leave this probably open, I will be pushing commits here until it is fully ready from my perspective. I can do mvn package and mvn install now, but it needs more :-)

Or as I suggested you could pull it into branch "feature/maven" so we keep it separated for some time.

**Comment by oreon3D** [comment]
alright no problem, I will create a dedicated branch for it and pull it

**Comment by archenroot** [comment]
Let me know your comments...

**Comment by oreon3D** [comment]
okay I created a branch 'maven integration', you can redirect the pull-request now. We can let it open until it is 100 % stable and then I merge it to master

**Comment by oreon3D** [comment]
I will do the upgrade to Lwjgl 3 within a dedicated branch. The upgrade will come along with primitive maven support just for the dependencies. When the engine is stable with lwjgl 3 I will merge the branch into master. After that you can adjust the feature/maven branch with the lwjgl 3 upgrade and resolve conflicts and finally the feature/maven branch (when it is stable) can be merged to master, is this a plan?

**Pull request closed without merging**
